# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:41+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Byline(BaseModel):
    organization: Optional[str] = None
    original: Optional[str] = None
    person: Optional[List] = None


class Headline(BaseModel):
    kicker: Optional[str] = None
    main: Optional[str] = None


class Keywords(BaseModel):
    name: Optional[str] = None
    rank: Optional[str] = None
    value: Optional[str] = None


class MultimediaItem(BaseModel):
    caption: Optional[str] = None
    copyright: Optional[str] = None
    format: Optional[str] = None
    height: Optional[int] = None
    subtype: Optional[str] = None
    type: Optional[str] = None
    url: Optional[str] = None
    width: Optional[int] = None


class Doc(BaseModel):
    field_id: Optional[str] = Field(None, alias='_id')
    abstract: Optional[str] = None
    blog: Optional[List] = None
    byline: Optional[Byline] = None
    document_type: Optional[str] = None
    headline: Optional[Headline] = None
    keywords: Optional[Keywords] = None
    lead_paragraph: Optional[str] = None
    multimedia: Optional[List[MultimediaItem]] = None
    news_desk: Optional[str] = None
    print_page: Optional[str] = None
    pub_date: Optional[str] = None
    section_name: Optional[str] = None
    slideshow_credits: Optional[str] = None
    snippet: Optional[str] = None
    source: Optional[str] = None
    subsection_name: Optional[str] = None
    type_of_material: Optional[str] = None
    web_url: Optional[str] = None
    word_count: Optional[str] = None


class Sort(Enum):
    newest = 'newest'
    oldest = 'oldest'
