# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:41+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import Doc


class Meta(BaseModel):
    hits: Optional[int] = None
    offset: Optional[int] = None
    time: Optional[int] = None


class Response(BaseModel):
    docs: Optional[List[Doc]] = None
    meta: Optional[Meta] = None


class JsonGetResponse(BaseModel):
    response: Optional[Response] = None
