# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:41+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from pydantic import conint

from models import Sort
from models.Articlesearch import JsonGetResponse

app = MCPProxy(
    description='With the Article Search API, you can search New York Times articles from Sept. 18, 1851 to today, retrieving headlines, abstracts, lead paragraphs, links to associated multimedia and other article metadata.  \n\n Note: In URI examples and field names, italics indicate placeholders for variables or values. Brackets [ ] indicate optional items. Parentheses ( ) are not a convention — when URIs include parentheses, interpret them literally.',
    termsOfService='http://developer.nytimes.com/tou',
    title='Article Search API',
    version='1.0.0',
    servers=[
        {'url': 'http://api.nytimes.com/svc/search/v2'},
        {'url': 'https://api.nytimes.com/svc/search/v2'},
    ],
)


@app.get(
    '/articlesearch.json',
    description=""" Article Search requests use the following URI structure:
 """,
    tags=['article_search_operations'],
    security=[
        APIKeyQuery(name="api-key"),
    ],
)
def get_articlesearch_json(
    q: Optional[str] = None,
    fq: Optional[str] = None,
    begin_date: Optional[str] = None,
    end_date: Optional[str] = None,
    sort: Optional[Sort] = None,
    fl: Optional[str] = None,
    hl: Optional[bool] = False,
    page: Optional[conint(ge=0, le=10)] = 0,
    facet_field: Optional[str] = None,
    facet_filter: Optional[bool] = False,
):
    """
    Article Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
